package es.uam.eps.sasi.passwordmanager;

import androidx.annotation.NonNull;
import androidx.room.ColumnInfo;
import androidx.room.Embedded;
import androidx.room.Entity;
import androidx.room.PrimaryKey;

@Entity(tableName = "site")
public class Site {
    @PrimaryKey
    @NonNull
    @ColumnInfo(name = "site_name")
    private String name;
    @ColumnInfo(name = "site_password")
    private String password;
    @Embedded
    private User user;
    @ColumnInfo(name = "site_autogenerated")
    private boolean autoGenerated;

    public Site(String name, String password, User user, boolean autoGenerated) {
        this.name = name;
        this.password = password;
        this.user = user;
        this.autoGenerated = autoGenerated;
    }

    // Getters and setters
    public String getName() { return this.name; }
    public String getPassword() { return this.password; }
    public User getUser() { return this.user; }
    public boolean isAutoGenerated() { return this.autoGenerated; }

    public void setName(String name) { this.name = name; }
    public void setPassword(String password) { this.password = password; }
    public void setAutoGenerated(boolean autoGenerated) { this.autoGenerated = autoGenerated; }
    public void setUser(User user) { this.user = user; }
}
